### ISSUE TITLE
Android package co.boundstate does not exist

### ISSUE THREAD

**Issue by raosaddam** [BranchMetrics/capacitor-branch-deep-links#41]
Im trying to implement branch links in my android app. After following every step here 

https://help.branch.io/developers-hub/docs/capacitor

Im getting these errors in MainActivity.java class 

`package co.boundstate does not exist`
`cannot find symbol class BranchDeepLinks`

![2021-05-26](https://user-images.githubusercontent.com/16712886/119713596-e2a2ea00-be2f-11eb-84e1-426231a5fb1d.png)

**Comment by raosaddam** [comment]
Had to build ionic project first and do npx cap sync android

**Comment by chiemekailo** [comment]
@raosaddam i have the same problem but your above steps did not help.
What i don't understand is that the error message say:
`<ionic project root>/node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/BridgeFragment.java:16: error: package co.boundstate does not exist
import co.boundstate.BranchDeepLinks;`

Why is it serching inside the `ionic-project-root/node_modules` instead of inside `android/app`?
I have looked in the android directory and there is no `com/getcapacitor/` subdirectory, so how come all other capacitor plugins are working?
Where are the capacitor plugins `.java` files located?

I am using capacitor v5.5
